SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `camat`;
CREATE TABLE `camat` (
  `id` int(11) NOT NULL,
  `province_id` int(11) NOT NULL,
  `regency_id` int(11) NOT NULL,
  `district_id` int(11) NOT NULL,
  `nip` varchar(20) NOT NULL,
  `nama` varchar(100) NOT NULL,
  `agama` tinyint(1) NOT NULL DEFAULT '1',
  `tmp_lhr` varchar(255) NOT NULL,
  `tgl_lhr` date NOT NULL,
  `gol` varchar(20) NOT NULL,
  `tmt` date NOT NULL,
  `pendidikan` tinyint(1) NOT NULL,
  `jurusan` varchar(100) NOT NULL,
  `univ` varchar(255) NOT NULL,
  `alamat` text NOT NULL,
  `kelamin` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `camat`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `camat`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
