SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `dilan_surat_pengajuan`;
CREATE TABLE `dilan_surat_pengajuan` (
  `id` int(11) NOT NULL,
  `desa_id` int(11) NOT NULL,
  `penduduk_id` int(11) NOT NULL,
  `dilan_surat_ket_id` int(11) NOT NULL,
  `keterangan` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `hp` varchar(20) NOT NULL,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `dilan_surat_pengajuan`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `dilan_surat_pengajuan`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
